### ISSUE TITLE
Wiki Review

### ISSUE THREAD

**Issue by mabelzhang** [osrf/vorc#3]
I'm opening this as an issue to track the task, since the Wiki isn't done via pull requests.

It'd be really helpful to get a few other hands to try out especially the installation tutorial on the Wiki.
@seankrag @crvogt this might be a good starting point when you are ready to jump on the boat.

Main page
https://github.com/osrf/vorc/wiki
It's a bit bare, I don't know if we want to move the tutorials to the main page. I was thinking leaving space for documents and other things, but now it seems those will go on the website instead. Then maybe this page looks better with the tutorials directly listed here. Feedback welcome.

Tutorials
https://github.com/osrf/vorc/wiki/tutorials
I've tested the [installation tutorial](https://github.com/osrf/vorc/wiki/Installation-on-Host) in a barebone `nvidia/opengl:1.0-glvnd-devel-ubuntu18.04` Docker image. All the steps up to and excluding the GUI also worked in a more barebone `ubuntu:bionic` Docker image (which doesn't have graphics).
So the installation should work if you run them on any Ubuntu 18.04 host machine.

Let me know if things don't work for you.
(We are assuming and only providing instructions for installing on host, as opposed to building and releasing a Docker image, due to time constraints.)

**Comment by seankrag** [comment]
Thanks, Mabel.

My main laptop is PopOS on Ubuntu 20.04 but I have another laptop running
standard Ubuntu 18.04. I'll give these install tutorials a try...

Sean

**Comment by crvogt** [comment]
Hey Mabel, 
Tried the installation on a standard Ubuntu 18.04 installation (not Docker). Only had one issue where gazebo would fail. Looks like it was because there was a version of gazebo already present. Solved by running `apt upgrade`.

**Comment by mabelzhang** [comment]
Thanks for trying it out! Do you remember if you ran `sudo apt full-upgrade` in the very beginning, and this still happens?

**Comment by crvogt** [comment]
I didn't skip any parts, so I'm *sure I ran that as well. Though it seems like gazebo would have been upgrade with that command, so it's making me doubt myself.

**Comment by mabelzhang** [comment]
Thanks! I will leave the instructions as is for now, and if anyone else complains, I'll add a troubleshoot section.

**Comment by seankrag** [comment]
Hi Mabel,

Sorry this is tardy, but I was finally able to get everything installed and
running on my Ubuntu 18.04 host. Instructions should work fine for a clean
18.04 setup. I encountered a few problems, but these were due to a previous
installation and some environment variables in my laptop's ~/.bahsrc file.

Best,
Sean

P.S. Documenting my issues below for posterity....

1) installed prerequisites fine, but saw apt messages saying my gazebo was
upgradable
2) colcon build threw an error while compiling wave_gazebo_plugins:
fatal error: sdf/sdf.hh: No such file or directory
3) tried another full-upgrade (because of #1 above): colcon build still had
fatal error
4) uninstalled gazebo9; reinstalled gazebo9; repeated all VORC setup
instructions: colcon build still failed
5) deleted build, install, and log directories
5) tried rebuilding with catkin_make instead: this worked!
6) sourced devel/setup.bash (catkin_make created devel instead of install)
7) roslaunch vorc_gazebo marina.launch: crashed due to prior robot's ROS_IP
address hard coded in my ~/.bashrc file
8) fixed ROS environment and roslaunch vorc_gazebo marina.launch works!
9) removed build, devel directories
10) tried building again with colcon build: now everything builds
successfully
11) sourced install/setup.bash
12) roslaunch vorc_gazebo marina.launch works!

Note: I began this process on my primary laptop, which runs Pop!_OS on
Ubuntu 20.04
This was a non-starter because dfault ros for 20.04 is ros-noetic; I
couldn't easily install ros-melodic, and hector_gazebo_plugins package
requires ros-melodic

**Comment by mabelzhang** [comment]
Thank you Sean for trying it out and the notes!

That is good to know - I did not know hector_gazebo_plugins requires Melodic.

I wonder if colcon would have also worked in step 5, after you cleaned the directories. It is good to see that colcon worked in step 10.
VRX was built with catkin and I changed to colcon for VORC because colcon is more modern. I hope they behave the same.

My takeaway from both of your trials is that we should set up a Dockerfile soon... ha, so that people have clean environments. Looks like pre-existing Gazebo versions can really make people's life frustrating. Cc @caguero 

I added a line near the top of the page so that people are warned.

Otherwise I think this issue can be closed.
